-- Bolá — Fight Club Training Engine, Fase 4: metadatos de ejercicios para
-- el motor + columnas nuevas en equipment/exercise_logs/body_measurements.
-- Generado por scratchpad/gen_fase4.cjs desde docs/exercise_metadata_source.md
-- (planilla del dueño) fusionada con los 90 ya cargados. Ver
-- docs/FIGHT_CLUB_TRAINING_ENGINE_AUDIT.md.
--
-- FUSIÓN (decisión del dueño 2026-09-10): 64 de la planilla ya existían
-- (nombre exacto o variante renombrada) y se ACTUALIZAN; 26 son nuevos y se
-- INSERTAN (sin contenido de técnica largo ni diagrama todavía, a pedido);
-- 26 de la DB que no están en la planilla (boxeo, movilidad, funcional)
-- reciben patrón + articulaciones de mejor esfuerzo. Cero borrados.

-- ==================== Columnas nuevas ====================
alter table public.exercises add column if not exists movement_pattern text;
alter table public.exercises add column if not exists secondary_muscles text[];
alter table public.exercises add column if not exists contraindicated_joints text[];
alter table public.exercises add column if not exists is_unilateral boolean not null default false;
alter table public.exercises add column if not exists is_active boolean not null default true;
alter table public.exercises add column if not exists required_equipment text[];

alter table public.equipment add column if not exists is_active boolean not null default true;

-- RIR/RPE por serie (pedido §19) — nullable, el modo entrenamiento suma un
-- campo opcional. No rompe nada de lo ya registrado.
alter table public.exercise_logs add column if not exists rir smallint check (rir between 0 and 10);
alter table public.exercise_logs add column if not exists rpe numeric(3,1) check (rpe between 0 and 10);

-- Cadera (pedido §5) — measurementForm() suma el campo.
alter table public.body_measurements add column if not exists hip_cm numeric(5,1);

-- ==================== UPDATE de los 90 ejercicios existentes ====================
update public.exercises set movement_pattern = 'empuje_horizontal', secondary_muscles = array['tríceps', 'deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['barra', 'banco']::text[] where gym_id is null and name = 'Press de banca con barra';
update public.exercises set movement_pattern = 'empuje_horizontal_inclinado', secondary_muscles = array['tríceps', 'deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['barra', 'banco']::text[] where gym_id is null and name = 'Press inclinado con barra';
update public.exercises set movement_pattern = 'empuje_horizontal', secondary_muscles = array['tríceps', 'deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['mancuernas', 'banco']::text[] where gym_id is null and name = 'Press de banca con mancuernas';
update public.exercises set movement_pattern = 'empuje_horizontal_inclinado', secondary_muscles = array['tríceps', 'deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['mancuernas', 'banco']::text[] where gym_id is null and name = 'Press inclinado con mancuernas';
update public.exercises set movement_pattern = 'aduccion_horizontal', secondary_muscles = array['deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['mancuernas', 'banco']::text[] where gym_id is null and name = 'Aperturas con mancuernas';
update public.exercises set movement_pattern = 'aduccion_horizontal', secondary_muscles = array['deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['polea']::text[] where gym_id is null and name = 'Cruce de poleas';
update public.exercises set movement_pattern = 'empuje_vertical', secondary_muscles = array['tríceps', 'deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['barra_fija']::text[] where gym_id is null and name = 'Fondos en paralelas';
update public.exercises set movement_pattern = 'empuje_horizontal', secondary_muscles = array['tríceps', 'deltoides anterior', 'core']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Flexiones';
update public.exercises set movement_pattern = 'empuje_horizontal', secondary_muscles = array['tríceps', 'deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Press en máquina';
update public.exercises set movement_pattern = 'traccion_vertical', secondary_muscles = array['bíceps', 'redondo mayor', 'romboides']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['barra_fija', 'barra']::text[] where gym_id is null and name = 'Dominadas';
update public.exercises set movement_pattern = 'traccion_vertical', secondary_muscles = array['bíceps', 'romboides']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['maquina_asistida']::text[] where gym_id is null and name = 'Dominadas asistidas';
update public.exercises set movement_pattern = 'traccion_vertical', secondary_muscles = array['bíceps', 'romboides']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['polea']::text[] where gym_id is null and name = 'Jalón al pecho';
update public.exercises set movement_pattern = 'traccion_horizontal', secondary_muscles = array['romboides', 'trapecio', 'bíceps']::text[], contraindicated_joints = array['columna_lumbar', 'hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['barra']::text[] where gym_id is null and name = 'Remo con barra';
update public.exercises set movement_pattern = 'traccion_horizontal', secondary_muscles = array['romboides', 'trapecio', 'bíceps']::text[], contraindicated_joints = array['columna_lumbar', 'hombro', 'codo']::text[], is_unilateral = true, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Remo con mancuerna';
update public.exercises set movement_pattern = 'traccion_horizontal', secondary_muscles = array['romboides', 'trapecio', 'bíceps']::text[], contraindicated_joints = array['hombro', 'codo', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['polea']::text[] where gym_id is null and name = 'Remo sentado en polea';
update public.exercises set movement_pattern = 'traccion_horizontal', secondary_muscles = array['romboides', 'trapecio', 'bíceps']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Remo en máquina';
update public.exercises set movement_pattern = 'extension_hombro', secondary_muscles = array['redondo mayor', 'tríceps largo']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['polea']::text[] where gym_id is null and name = 'Pullover en polea';
update public.exercises set movement_pattern = 'bisagra_cadera', secondary_muscles = array['glúteos', 'erectores espinales']::text[], contraindicated_joints = array['columna_lumbar', 'cadera', 'rodilla']::text[], is_unilateral = false, required_equipment = array['barra']::text[] where gym_id is null and name = 'Peso muerto rumano';
update public.exercises set movement_pattern = 'empuje_vertical', secondary_muscles = array['tríceps', 'deltoides lateral']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['barra']::text[] where gym_id is null and name = 'Press militar con barra';
update public.exercises set movement_pattern = 'empuje_vertical', secondary_muscles = array['tríceps', 'deltoides lateral']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Press de hombros con mancuernas';
update public.exercises set movement_pattern = 'abduccion_hombro', secondary_muscles = array['trapecio superior']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Elevaciones laterales';
update public.exercises set movement_pattern = 'abduccion_hombro', secondary_muscles = array['trapecio superior']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = true, required_equipment = array['polea']::text[] where gym_id is null and name = 'Elevaciones laterales en polea';
update public.exercises set movement_pattern = 'abduccion_horizontal', secondary_muscles = array['romboides', 'trapecio']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Pájaros con mancuernas';
update public.exercises set movement_pattern = 'rotacion_externa', secondary_muscles = array['trapecio', 'romboides']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['polea', 'cuerda_saltar']::text[] where gym_id is null and name = 'Face pull';
update public.exercises set movement_pattern = 'flexion_codo', secondary_muscles = array['braquial', 'braquiorradial']::text[], contraindicated_joints = array['codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['barra']::text[] where gym_id is null and name = 'Curl de bíceps con barra';
update public.exercises set movement_pattern = 'flexion_codo', secondary_muscles = array['braquial', 'braquiorradial']::text[], contraindicated_joints = array['codo', 'muñeca']::text[], is_unilateral = true, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Curl alterno con mancuernas';
update public.exercises set movement_pattern = 'flexion_codo', secondary_muscles = array['bíceps', 'braquiorradial']::text[], contraindicated_joints = array['codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Curl martillo';
update public.exercises set movement_pattern = 'flexion_codo', secondary_muscles = array['braquial']::text[], contraindicated_joints = array['codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['banco_predicador', 'banco']::text[] where gym_id is null and name = 'Curl predicador';
update public.exercises set movement_pattern = 'flexion_codo', secondary_muscles = array['braquial']::text[], contraindicated_joints = array['codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['polea']::text[] where gym_id is null and name = 'Curl en polea';
update public.exercises set movement_pattern = 'empuje_horizontal', secondary_muscles = array['pectoral', 'deltoides anterior']::text[], contraindicated_joints = array['hombro', 'codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['barra', 'banco']::text[] where gym_id is null and name = 'Press cerrado';
update public.exercises set movement_pattern = 'extension_codo', secondary_muscles = array[]::text[], contraindicated_joints = array['codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['polea', 'cuerda_saltar']::text[] where gym_id is null and name = 'Extensión de tríceps en polea';
update public.exercises set movement_pattern = 'extension_codo', secondary_muscles = array[]::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Extensión de tríceps sobre cabeza';
update public.exercises set movement_pattern = 'extension_codo', secondary_muscles = array[]::text[], contraindicated_joints = array['codo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['barra_ez', 'banco']::text[] where gym_id is null and name = 'Press francés';
update public.exercises set movement_pattern = 'extension_codo', secondary_muscles = array[]::text[], contraindicated_joints = array['codo', 'hombro']::text[], is_unilateral = true, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Patada de tríceps';
update public.exercises set movement_pattern = 'sentadilla', secondary_muscles = array['glúteos', 'isquiotibiales', 'core']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['barra']::text[] where gym_id is null and name = 'Sentadilla con barra';
update public.exercises set movement_pattern = 'sentadilla', secondary_muscles = array['glúteos', 'core']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo', 'muñeca']::text[], is_unilateral = false, required_equipment = array['barra']::text[] where gym_id is null and name = 'Sentadilla frontal';
update public.exercises set movement_pattern = 'empuje_pierna', secondary_muscles = array['glúteos', 'isquiotibiales']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo']::text[], is_unilateral = false, required_equipment = array['prensa']::text[] where gym_id is null and name = 'Prensa de piernas';
update public.exercises set movement_pattern = 'zancada', secondary_muscles = array['glúteos', 'isquiotibiales']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo']::text[], is_unilateral = true, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Zancadas caminando';
update public.exercises set movement_pattern = 'zancada', secondary_muscles = array['glúteos', 'isquiotibiales']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo']::text[], is_unilateral = true, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Split squat búlgaro';
update public.exercises set movement_pattern = 'extension_rodilla', secondary_muscles = array[]::text[], contraindicated_joints = array['rodilla']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Extensión de piernas';
update public.exercises set movement_pattern = 'flexion_rodilla', secondary_muscles = array['gemelos']::text[], contraindicated_joints = array['rodilla', 'cadera']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Curl femoral tumbado';
update public.exercises set movement_pattern = 'flexion_rodilla', secondary_muscles = array['gemelos']::text[], contraindicated_joints = array['rodilla', 'cadera']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Curl femoral sentado';
update public.exercises set movement_pattern = 'bisagra_cadera', secondary_muscles = array['glúteos', 'erectores espinales']::text[], contraindicated_joints = array['columna_lumbar', 'cadera', 'rodilla']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Peso muerto con mancuernas';
update public.exercises set movement_pattern = 'zancada', secondary_muscles = array['glúteos', 'isquiotibiales']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo']::text[], is_unilateral = true, required_equipment = array['mancuernas', 'banco']::text[] where gym_id is null and name = 'Step-up';
update public.exercises set movement_pattern = 'sentadilla', secondary_muscles = array['glúteos']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo']::text[], is_unilateral = false, required_equipment = array['maquina_hack']::text[] where gym_id is null and name = 'Sentadilla hack';
update public.exercises set movement_pattern = 'extension_cadera', secondary_muscles = array['isquiotibiales', 'aductores']::text[], contraindicated_joints = array['cadera', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['barra']::text[] where gym_id is null and name = 'Hip thrust con barra';
update public.exercises set movement_pattern = 'extension_cadera', secondary_muscles = array['isquiotibiales']::text[], contraindicated_joints = array['cadera', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Puente de glúteos';
update public.exercises set movement_pattern = 'abduccion_cadera', secondary_muscles = array['glúteo menor']::text[], contraindicated_joints = array['cadera']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Abducción de cadera';
update public.exercises set movement_pattern = 'flexion_plantar', secondary_muscles = array['sóleo']::text[], contraindicated_joints = array['tobillo', 'rodilla']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Elevación de talones de pie';
update public.exercises set movement_pattern = 'flexion_plantar', secondary_muscles = array['gastrocnemio']::text[], contraindicated_joints = array['tobillo', 'rodilla']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Elevación de talones sentado';
update public.exercises set movement_pattern = 'flexion_tronco', secondary_muscles = array['oblicuos']::text[], contraindicated_joints = array['columna_cervical', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Crunch';
update public.exercises set movement_pattern = 'flexion_tronco', secondary_muscles = array['oblicuos']::text[], contraindicated_joints = array['columna_lumbar']::text[], is_unilateral = false, required_equipment = array['polea']::text[] where gym_id is null and name = 'Crunch en polea';
update public.exercises set movement_pattern = 'flexion_cadera', secondary_muscles = array['flexores de cadera']::text[], contraindicated_joints = array['cadera', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['barra_fija', 'barra']::text[] where gym_id is null and name = 'Elevación de piernas';
update public.exercises set movement_pattern = 'flexion_cadera', secondary_muscles = array['flexores de cadera']::text[], contraindicated_joints = array['cadera', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['barra_fija', 'barra']::text[] where gym_id is null and name = 'Elevación de rodillas';
update public.exercises set movement_pattern = 'isometrico', secondary_muscles = array['recto abdominal', 'oblicuos']::text[], contraindicated_joints = array['hombro', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Plancha';
update public.exercises set movement_pattern = 'isometrico', secondary_muscles = array['core', 'glúteo medio']::text[], contraindicated_joints = array['hombro', 'columna_lumbar', 'cadera']::text[], is_unilateral = true, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Plancha lateral';
update public.exercises set movement_pattern = 'elevacion_escapular', secondary_muscles = array['elevador de la escápula']::text[], contraindicated_joints = array['hombro', 'cuello']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Encogimientos con mancuernas';
update public.exercises set movement_pattern = 'transporte', secondary_muscles = array['trapecio', 'core', 'hombros']::text[], contraindicated_joints = array['hombro', 'muñeca', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Farmer walk';
update public.exercises set movement_pattern = 'pliometria', secondary_muscles = array['pecho', 'piernas', 'core', 'hombros']::text[], contraindicated_joints = array['rodilla', 'tobillo', 'hombro', 'muñeca']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Burpees';
update public.exercises set movement_pattern = 'cardio_dinamico', secondary_muscles = array['hombros', 'flexores de cadera', 'piernas']::text[], contraindicated_joints = array['hombro', 'muñeca', 'cadera']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Mountain climbers';
update public.exercises set movement_pattern = 'cardio_dinamico', secondary_muscles = array['pantorrillas', 'hombros']::text[], contraindicated_joints = array['tobillo', 'rodilla', 'hombro']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Jumping jacks';
update public.exercises set movement_pattern = 'saltos', secondary_muscles = array['cuádriceps', 'core', 'hombros']::text[], contraindicated_joints = array['tobillo', 'rodilla', 'muñeca']::text[], is_unilateral = false, required_equipment = array['cuerda_saltar']::text[] where gym_id is null and name = 'Cuerda de saltar';
update public.exercises set movement_pattern = 'carrera', secondary_muscles = array['glúteos', 'core', 'pantorrillas']::text[], contraindicated_joints = array['rodilla', 'tobillo', 'cadera']::text[], is_unilateral = false, required_equipment = array['cinta']::text[] where gym_id is null and name = 'Sprint en cinta';
update public.exercises set movement_pattern = 'marcha', secondary_muscles = array['glúteos', 'pantorrillas']::text[], contraindicated_joints = array['rodilla', 'tobillo', 'cadera']::text[], is_unilateral = false, required_equipment = array['cinta']::text[] where gym_id is null and name = 'Caminata inclinada';
update public.exercises set movement_pattern = 'sentadilla', secondary_muscles = array['glúteos', 'core']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo']::text[], is_unilateral = false, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Sentadilla goblet';
update public.exercises set movement_pattern = 'zancada', secondary_muscles = array['glúteos', 'isquiotibiales']::text[], contraindicated_joints = array['rodilla', 'cadera', 'tobillo']::text[], is_unilateral = true, required_equipment = array['mancuernas']::text[] where gym_id is null and name = 'Zancada atrás';
update public.exercises set movement_pattern = 'aduccion_cadera', secondary_muscles = array[]::text[], contraindicated_joints = array['cadera']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Aducción de cadera';
update public.exercises set movement_pattern = 'empuje_vertical', secondary_muscles = array['tríceps', 'deltoides lateral']::text[], contraindicated_joints = array['hombro', 'codo']::text[], is_unilateral = false, required_equipment = array['maquina']::text[] where gym_id is null and name = 'Press de hombros en máquina';
update public.exercises set movement_pattern = 'antirotacion', secondary_muscles = array['transverso abdominal']::text[], contraindicated_joints = array['columna_lumbar']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Dead bug';
update public.exercises set movement_pattern = 'antirotacion', secondary_muscles = array['glúteos', 'erectores espinales']::text[], contraindicated_joints = array['columna_lumbar', 'hombro']::text[], is_unilateral = true, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Bird dog';
update public.exercises set movement_pattern = 'cardio_ciclico', secondary_muscles = array['glúteos', 'pantorrillas']::text[], contraindicated_joints = array['rodilla']::text[], is_unilateral = false, required_equipment = array['bicicleta']::text[] where gym_id is null and name = 'Bicicleta estática';
update public.exercises set movement_pattern = 'cardio_ciclico', secondary_muscles = array['espalda', 'piernas', 'core']::text[], contraindicated_joints = array['columna_lumbar', 'rodilla']::text[], is_unilateral = false, required_equipment = array['remo_ergometro']::text[] where gym_id is null and name = 'Remo ergómetro';
update public.exercises set movement_pattern = 'cardio_dinamico', secondary_muscles = array['hombros', 'core']::text[], contraindicated_joints = array['hombro']::text[], is_unilateral = false, required_equipment = array['battle_ropes']::text[] where gym_id is null and name = 'Battle ropes';
update public.exercises set movement_pattern = 'bisagra_cadera', secondary_muscles = array['glúteos', 'core', 'hombros']::text[], contraindicated_joints = array['columna_lumbar', 'cadera', 'hombro']::text[], is_unilateral = false, required_equipment = array['kettlebell']::text[] where gym_id is null and name = 'Kettlebell swing';
update public.exercises set movement_pattern = 'explosivo', secondary_muscles = array['core', 'hombros', 'piernas']::text[], contraindicated_joints = array['hombro', 'muñeca', 'cadera']::text[], is_unilateral = true, required_equipment = array['kettlebell']::text[] where gym_id is null and name = 'Turkish get-up';
update public.exercises set movement_pattern = 'explosivo', secondary_muscles = array['glúteos', 'trapecio', 'core']::text[], contraindicated_joints = array['columna_lumbar', 'hombro', 'muñeca']::text[], is_unilateral = false, required_equipment = array['kettlebell']::text[] where gym_id is null and name = 'Clean con kettlebell';
update public.exercises set movement_pattern = 'pliometria', secondary_muscles = array['glúteos', 'pantorrillas', 'core']::text[], contraindicated_joints = array['rodilla', 'tobillo']::text[], is_unilateral = false, required_equipment = array['cajon']::text[] where gym_id is null and name = 'Box jump';
update public.exercises set movement_pattern = 'explosivo', secondary_muscles = array['core', 'hombros', 'piernas']::text[], contraindicated_joints = array['hombro', 'columna_lumbar']::text[], is_unilateral = false, required_equipment = array['balon_medicinal']::text[] where gym_id is null and name = 'Lanzamiento de balón medicinal';
update public.exercises set movement_pattern = 'boxeo', secondary_muscles = array['hombros', 'core']::text[], contraindicated_joints = array['hombro', 'muñeca']::text[], is_unilateral = false, required_equipment = array['saco_boxeo']::text[] where gym_id is null and name = 'Golpes al saco';
update public.exercises set movement_pattern = 'boxeo', secondary_muscles = array['hombros', 'core', 'piernas']::text[], contraindicated_joints = array['hombro']::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Sombra de boxeo';
update public.exercises set movement_pattern = 'boxeo', secondary_muscles = array['hombros', 'core']::text[], contraindicated_joints = array['hombro', 'muñeca']::text[], is_unilateral = false, required_equipment = array['saco_boxeo', 'guantes']::text[] where gym_id is null and name = 'Combinación jab-cross';
update public.exercises set movement_pattern = 'boxeo', secondary_muscles = array['core', 'hombros']::text[], contraindicated_joints = array['hombro', 'muñeca']::text[], is_unilateral = false, required_equipment = array['saco_boxeo', 'guantes']::text[] where gym_id is null and name = 'Hook al saco';
update public.exercises set movement_pattern = 'boxeo', secondary_muscles = array['core', 'hombros']::text[], contraindicated_joints = array['hombro', 'muñeca']::text[], is_unilateral = false, required_equipment = array['saco_boxeo', 'guantes']::text[] where gym_id is null and name = 'Uppercut al saco';
update public.exercises set movement_pattern = 'pliometria', secondary_muscles = array['pecho', 'piernas', 'core', 'hombros']::text[], contraindicated_joints = array['rodilla', 'tobillo', 'hombro', 'muñeca']::text[], is_unilateral = false, required_equipment = array['peso_corporal', 'saco_boxeo']::text[] where gym_id is null and name = 'Burpee + golpe';
update public.exercises set movement_pattern = 'movilidad', secondary_muscles = array[]::text[], contraindicated_joints = array[]::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Movilidad de tobillo';
update public.exercises set movement_pattern = 'movilidad', secondary_muscles = array[]::text[], contraindicated_joints = array[]::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Rotación torácica';
update public.exercises set movement_pattern = 'movilidad', secondary_muscles = array[]::text[], contraindicated_joints = array[]::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Estiramiento flexor de cadera';
update public.exercises set movement_pattern = 'movilidad', secondary_muscles = array[]::text[], contraindicated_joints = array[]::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Estiramiento de isquiotibiales';
update public.exercises set movement_pattern = 'movilidad', secondary_muscles = array[]::text[], contraindicated_joints = array[]::text[], is_unilateral = false, required_equipment = array['peso_corporal']::text[] where gym_id is null and name = 'Estiramiento de pectoral';
update public.exercises set movement_pattern = 'movilidad', secondary_muscles = array[]::text[], contraindicated_joints = array[]::text[], is_unilateral = false, required_equipment = array['banco']::text[] where gym_id is null and name = 'Estiramiento de dorsal';

-- ==================== INSERT de los 26 ejercicios nuevos ====================
-- Mismas 11 columnas base que 20260908000200 + las 4 del motor.
insert into public.exercises
  (gym_id, name, muscle_group, equipment_name, level, goal, kind, description, suggested_sets, suggested_reps, suggested_rest_seconds, movement_pattern, secondary_muscles, contraindicated_joints, is_unilateral, required_equipment)
values
  (null, 'Press declinado con barra', 'Pecho', 'Barra + banco', 'Intermedio', 'Hipertrofia', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'empuje_horizontal_declinado', array['tríceps', 'deltoides anterior']::text[], array['hombro', 'codo', 'muñeca']::text[], false, array['barra', 'banco']::text[]),
  (null, 'Peso muerto convencional', 'Espalda', 'Barra', 'Avanzado', 'Fuerza/Hipertrofia', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'bisagra_cadera', array['glúteos', 'isquiotibiales', 'trapecio', 'core']::text[], array['columna_lumbar', 'cadera', 'rodilla']::text[], false, array['barra']::text[]),
  (null, 'Press Arnold', 'Hombros', 'Mancuernas', 'Intermedio', 'Hipertrofia', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'empuje_vertical', array['deltoides lateral', 'tríceps']::text[], array['hombro', 'codo', 'muñeca']::text[], false, array['mancuernas']::text[]),
  (null, 'Elevación frontal', 'Hombros', 'Mancuernas', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'flexion_hombro', array['pectoral superior']::text[], array['hombro', 'codo']::text[], false, array['mancuernas']::text[]),
  (null, 'Curl con mancuernas', 'Bíceps', 'Mancuernas', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'flexion_codo', array['braquial', 'braquiorradial']::text[], array['codo', 'muñeca']::text[], false, array['mancuernas']::text[]),
  (null, 'Curl concentrado', 'Bíceps', 'Mancuerna', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'flexion_codo', array['braquial']::text[], array['codo', 'muñeca']::text[], true, array['mancuernas']::text[]),
  (null, 'Fondos para tríceps', 'Tríceps', 'Paralelas', 'Intermedio', 'Fuerza/Hipertrofia', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'empuje_vertical', array['pectoral', 'deltoides anterior']::text[], array['hombro', 'codo', 'muñeca']::text[], false, array['barra_fija']::text[]),
  (null, 'Sentadilla sumo', 'Piernas', 'Barra', 'Principiante', 'Hipertrofia', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'sentadilla', array['glúteos', 'cuádriceps', 'isquiotibiales']::text[], array['cadera', 'rodilla', 'tobillo']::text[], false, array['barra']::text[]),
  (null, 'Buenos días con barra', 'Piernas', 'Barra', 'Avanzado', 'Fuerza', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'bisagra_cadera', array['glúteos', 'erectores espinales']::text[], array['columna_lumbar', 'cadera']::text[], false, array['barra']::text[]),
  (null, 'Extensión de cadera en máquina', 'Glúteos', 'Máquina', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'extension_cadera', array['isquiotibiales']::text[], array['cadera', 'columna_lumbar']::text[], false, array['maquina']::text[]),
  (null, 'Patada de glúteo en polea', 'Glúteos', 'Polea', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'extension_cadera', array['isquiotibiales']::text[], array['cadera', 'columna_lumbar']::text[], true, array['polea']::text[]),
  (null, 'Abducción de cadera en polea', 'Glúteos', 'Polea', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'abduccion_cadera', array['glúteo menor']::text[], array['cadera']::text[], true, array['polea']::text[]),
  (null, 'Elevación de talones en prensa', 'Pantorrillas', 'Prensa', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'flexion_plantar', array['sóleo']::text[], array['tobillo', 'rodilla']::text[], false, array['prensa']::text[]),
  (null, 'Elevación unilateral de talones', 'Pantorrillas', 'Peso corporal', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'flexion_plantar', array['sóleo']::text[], array['tobillo', 'rodilla']::text[], true, array['peso_corporal']::text[]),
  (null, 'Russian twist', 'Core', 'Peso corporal', 'Intermedio', 'Core', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'rotacion_tronco', array['recto abdominal']::text[], array['columna_lumbar', 'cadera']::text[], false, array['peso_corporal']::text[]),
  (null, 'Pallof press', 'Core', 'Polea', 'Principiante', 'Core/Control motor', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'antirotacion', array['oblicuos', 'transverso abdominal']::text[], array['hombro', 'codo', 'columna_lumbar']::text[], false, array['polea']::text[]),
  (null, 'Encogimientos con barra', 'Trapecios', 'Barra', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'elevacion_escapular', array['elevador de la escápula']::text[], array['hombro', 'cuello']::text[], false, array['barra']::text[]),
  (null, 'Curl inverso', 'Antebrazos', 'Barra', 'Intermedio', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'flexion_codo', array['extensores de muñeca', 'bíceps']::text[], array['codo', 'muñeca']::text[], false, array['barra']::text[]),
  (null, 'Remo al mentón con cable', 'Hombros', 'Polea', 'Intermedio', 'Hipertrofia', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'traccion_vertical', array['trapecio', 'bíceps']::text[], array['hombro', 'codo', 'muñeca']::text[], false, array['polea']::text[]),
  (null, 'Rotación externa con polea', 'Hombros', 'Polea', 'Principiante', 'Salud de hombro', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'rotacion_externa', array['deltoides posterior']::text[], array['hombro', 'codo']::text[], true, array['polea']::text[]),
  (null, 'Rotación interna con polea', 'Hombros', 'Polea', 'Principiante', 'Salud de hombro', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'rotacion_interna', array['pectoral', 'dorsal']::text[], array['hombro', 'codo']::text[], true, array['polea']::text[]),
  (null, 'Extensión de muñeca', 'Antebrazos', 'Mancuerna', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'extension_muñeca', array[]::text[], array['muñeca', 'codo']::text[], false, array['mancuernas']::text[]),
  (null, 'Flexión de muñeca', 'Antebrazos', 'Mancuerna', 'Principiante', 'Hipertrofia', 'Aislamiento', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'flexion_muñeca', array[]::text[], array['muñeca', 'codo']::text[], false, array['mancuernas']::text[]),
  (null, 'Buenos días con peso corporal', 'Piernas', 'Peso corporal', 'Principiante', 'Movilidad/Fuerza', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'bisagra_cadera', array['glúteos', 'erectores espinales']::text[], array['columna_lumbar', 'cadera']::text[], false, array['peso_corporal']::text[]),
  (null, 'Sentadilla con peso corporal', 'Piernas', 'Peso corporal', 'Principiante', 'Resistencia', 'Compuesto', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'sentadilla', array['glúteos', 'isquiotibiales', 'core']::text[], array['rodilla', 'cadera', 'tobillo']::text[], false, array['peso_corporal']::text[]),
  (null, 'Zancada con peso corporal', 'Piernas', 'Peso corporal', 'Principiante', 'Resistencia', 'Unilateral', 'Ejecuta el movimiento con control, rango cómodo y técnica estable.', 3, '8-12', 90, 'zancada', array['glúteos', 'isquiotibiales']::text[], array['rodilla', 'cadera', 'tobillo']::text[], true, array['peso_corporal']::text[]);
